### ISSUE TITLE
Does not find missing clients

### ISSUE THREAD

**Issue by FransUrbo** [rikonor/salt-mine-refresh#1]
If/when a salt minion is no more, <code>salt "*" saltutil.sync_all</code> will return:

```
Minion did not return. [Not connected]
```

That's because there is no <code>mine.p</code> in those/that directory (<code>/var/cache/salt/master/minions/missing_minion</code>).

If we instead look for <code>data.p</code> in https://github.com/rikonor/salt-mine-refresh/blob/master/mine.py#L58, we get ALL.

We also need to delete the whole directory, not just the file.

**Comment by FransUrbo** [comment]
However, even with this change, I still get the <code>Minion did not return</code>.

**Comment by rikonor** [comment]
@FransUrbo, I haven't maintained this project in a while.
If you figure it out, please file a PR and I'll be happy to include it.

**Comment by FransUrbo** [comment]
I did...
